// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	messages.proto
	services.proto

It has these top-level messages:
	Header
	Field
	BytesMessage
	FieldsMessage
	Status
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Field struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BytesMessage struct {
	Headers []*Header `protobuf:"bytes,1,rep,name=headers" json:"headers,omitempty"`
	Data    []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *BytesMessage) Reset()                    { *m = BytesMessage{} }
func (m *BytesMessage) String() string            { return proto.CompactTextString(m) }
func (*BytesMessage) ProtoMessage()               {}
func (*BytesMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BytesMessage) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *BytesMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FieldsMessage struct {
	Headers []*Header `protobuf:"bytes,1,rep,name=headers" json:"headers,omitempty"`
	Fields  []*Field  `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty"`
}

func (m *FieldsMessage) Reset()                    { *m = FieldsMessage{} }
func (m *FieldsMessage) String() string            { return proto.CompactTextString(m) }
func (*FieldsMessage) ProtoMessage()               {}
func (*FieldsMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FieldsMessage) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *FieldsMessage) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "protobuf.Header")
	proto.RegisterType((*Field)(nil), "protobuf.Field")
	proto.RegisterType((*BytesMessage)(nil), "protobuf.BytesMessage")
	proto.RegisterType((*FieldsMessage)(nil), "protobuf.FieldsMessage")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5,
	0x69, 0x4a, 0x46, 0x5c, 0x6c, 0x1e, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b,
	0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13, 0x58, 0x10, 0xc2, 0x51, 0x32, 0xe4, 0x62, 0x75, 0xcb,
	0x4c, 0xcd, 0x49, 0x21, 0x41, 0x8b, 0x1f, 0x17, 0x8f, 0x53, 0x65, 0x49, 0x6a, 0xb1, 0x2f, 0xc4,
	0x1d, 0x42, 0x5a, 0x5c, 0xec, 0x19, 0x60, 0x6b, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d,
	0x04, 0xf4, 0x60, 0x4e, 0xd2, 0x83, 0xb8, 0x27, 0x08, 0xa6, 0x00, 0x64, 0x4b, 0x4a, 0x62, 0x49,
	0x22, 0xd8, 0x40, 0x9e, 0x20, 0x30, 0x5b, 0x29, 0x85, 0x8b, 0x17, 0xec, 0x04, 0xb2, 0x0c, 0x54,
	0xe7, 0x62, 0x4b, 0x03, 0x6b, 0x96, 0x60, 0x02, 0x2b, 0xe5, 0x47, 0x28, 0x05, 0x1b, 0x1a, 0x04,
	0x95, 0x76, 0x92, 0xe3, 0x82, 0x07, 0x94, 0x13, 0x47, 0x00, 0x88, 0xe5, 0x54, 0x9a, 0x16, 0x05,
	0x17, 0x4b, 0x62, 0x03, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0x63, 0xde, 0x36,
	0x5f, 0x01, 0x00, 0x00,
}
